const { chromium } = require('playwright');
const path = require('node:path');
const fs = require('node:fs');
(async()=>{
  const browser=await chromium.launch({headless:true});
  const page=await browser.newPage({viewport:{width:1440,height:1000}});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  const {ready,seekPreview}=require('./preview_test_helpers.cjs');
  const waitReady=()=>ready(page);
  await page.goto(process.env.FALA_UI_URL||'http://127.0.0.1:5173');
  await page.getByText('Processamento local',{exact:true}).waitFor();
  await page.locator('input[type=file]').first().setInputFiles(path.resolve('outputs/teste-original.mp4'));
  await page.locator('.media-info').getByText('teste-original.mp4',{exact:true}).waitFor();
  await page.waitForFunction(()=>[...document.querySelectorAll('.filmstrip img')].some(i=>i.complete&&i.naturalWidth>0));
  await page.waitForFunction(()=>!document.querySelector('.job'));
  if(!(await page.getByRole('button',{name:'Excluir intervalo',exact:true}).isDisabled()))throw Error('Corte manual sem seleção habilitado');
  await page.getByLabel('Início do intervalo',{exact:true}).fill('1');
  await page.getByLabel('Fim do intervalo',{exact:true}).fill('2');
  await page.getByRole('button',{name:'Excluir intervalo',exact:true}).click();
  await waitReady();
  if(await page.locator('.cut-row').count()!==1)throw Error('Corte sem transcrição falhou');
  await page.getByRole('button',{name:'Desfazer',exact:true}).click();
  await waitReady();
  if(await page.locator('.cut-row').count())throw Error('Desfazer corte manual falhou');
  await page.locator('.source-selection summary').click();
  await page.locator('.wave').scrollIntoViewIfNeeded();
  const wave=await page.locator('.wave').boundingBox();
  await page.mouse.move(wave.x+wave.width/6,wave.y+20);
  await page.mouse.down();await page.mouse.move(wave.x+wave.width/3,wave.y+20,{steps:8});await page.mouse.up();
  if(!(await page.locator('.interval-highlight').count()))throw Error('Seleção por arraste na linha do tempo falhou');
  await page.locator('.wave').focus();await page.keyboard.press('Delete');
  await waitReady();
  if(await page.locator('.cut-row').count()!==1)throw Error('Delete na linha do tempo falhou');
  await page.getByRole('button',{name:'Desfazer',exact:true}).click();
  await waitReady();
  const words=['Teste','de','edição','local'].map((text,i)=>({id:'word'+i,text,start:i,end:i+.8,paragraph:0}));
  const project={version:1,videoPath:path.resolve('outputs/teste-original.mp4'),edit:{words,cuts:[]}};
  fs.writeFileSync('outputs/projeto-teste.json',JSON.stringify(project));
  await page.locator('input[type=file]').nth(1).setInputFiles(path.resolve('outputs/projeto-teste.json'));
  await page.locator('.word').first().waitFor();
  await page.waitForFunction(()=>!document.querySelector('.job'));
  await page.locator('.word').nth(1).click();
  await page.locator('.word').nth(2).click({modifiers:['Shift']});
  await page.getByRole('button',{name:'Excluir trecho',exact:true}).click();
  await waitReady();
  if(await page.locator('.word.deleted').count()!==2)throw Error('Seleção/exclusão falhou');
  await page.getByRole('button',{name:'Desfazer',exact:true}).click();
  await waitReady();
  if(await page.locator('.word.deleted').count()!==0)throw Error('Desfazer falhou');
  await page.getByRole('button',{name:'Refazer',exact:true}).click();
  await waitReady();
  await page.getByRole('button',{name:'Restaurar',exact:true}).click();
  await waitReady();
  if(await page.locator('.word.deleted').count()!==0)throw Error('Restaurar falhou');
  await page.locator('.word').first().click();
  await page.getByLabel('Texto corrigido').fill('Correção');
  await page.getByRole('button',{name:'Corrigir texto',exact:true}).click();
  if(await page.locator('.word').first().textContent()!=='Correção ')throw Error('Correção falhou');
  await page.locator('.word').nth(1).focus();await page.keyboard.press('Delete');
  await waitReady();
  if(await page.locator('.word.deleted').count()!==1)throw Error('Delete falhou');
  if(!(await page.locator('.word').nth(1).evaluate(el=>el.classList.contains('deleted'))))throw Error('Delete excluiu a palavra errada');
  if(await page.locator('.word').nth(1).getAttribute('aria-pressed')!=='true')throw Error('Seleção visual não acompanhou o Delete');
  await page.getByLabel('Buscar palavras').fill('local');
  if(await page.locator('.word.match').count()!==1)throw Error('Busca falhou');
  await page.getByLabel('Fim',{exact:true}).fill('2');
  await page.getByLabel('Fim',{exact:true}).press('Tab');
  await waitReady();
  await page.getByLabel('Início',{exact:true}).fill('1');
  await page.getByLabel('Início',{exact:true}).press('Tab');
  await waitReady();
  await seekPreview(page,1.2);await page.getByTitle('Reproduzir prévia',{exact:true}).click();
  await page.waitForFunction(()=>Number(document.querySelector('.player-position').value)>=2);
  await page.getByTitle('Pausar prévia',{exact:true}).click();
  if(await page.getByRole('button',{name:/^(Original|Editada)$/}).count())throw Error('Previa unica ainda possui seletor');
  await page.screenshot({path:'outputs/interface-desktop.png',fullPage:true});
  await page.setViewportSize({width:600,height:900});
  await page.screenshot({path:'outputs/interface-compacta.png',fullPage:true});
  const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth);
  if(overflow)throw Error('Layout transborda');
  if(errors.length)throw Error(errors.join('\n'));
  await page.getByRole('button',{name:'Exportar MP4',exact:true}).click();
  await page.getByText(/Exportação concluída:/).waitFor({timeout:60000});
  await page.locator('input[type=file]').first().setInputFiles(path.resolve('outputs/respiracoes-teste.mp4'));
  await page.locator('.media-info').getByText('respiracoes-teste.mp4',{exact:true}).waitFor();
  await page.waitForFunction(()=>!document.querySelector('.job'));
  await page.locator('.breath-review summary').click();
  await page.getByRole('button',{name:'Detectar respirações',exact:true}).click();
  await page.getByRole('heading',{name:'Possíveis respirações'}).waitFor({timeout:60000});
  const candidate=page.getByRole('checkbox').first();await candidate.waitFor();
  if(await page.locator('section.cut-list').last().locator('.cut-row').count())throw Error('Análise aplicou cortes sem aprovação');
  await candidate.check();await page.getByRole('button',{name:'Excluir selecionados',exact:true}).click();
  await waitReady();
  if(!(await page.locator('.cut-row').count()))throw Error('Respiração selecionada não virou corte');
  await page.getByRole('button',{name:'Desfazer',exact:true}).click();
  await waitReady();
  if(await page.locator('.cut-row').count())throw Error('Corte de respiração não é reversível');
  await page.getByRole('button',{name:'Detectar respirações',exact:true}).click();
  await page.getByRole('heading',{name:'Possíveis respirações'}).waitFor({timeout:60000});
  const total=await page.getByRole('checkbox').count();
  if(!total)throw Error('Não há candidatos para testar exclusão em lote');
  if(await page.getByRole('checkbox').first().isChecked())throw Error('Candidato já estava selecionado');
  await page.getByRole('button',{name:'Ouvir',exact:true}).first().click();
  await page.evaluate(()=>document.querySelector('video').pause());
  await page.getByRole('button',{name:'Excluir todas',exact:true}).click();
  await waitReady();
  if(await page.locator('.cut-row').count()!==total)throw Error('Excluir todas não aplicou o lote inteiro');
  if(await page.evaluate(()=>!document.querySelector('audio').paused))throw Error('Exclusao deixou audicao ativa');
  if(await page.locator('.player-position').evaluate(e=>Number(e.max))>=6)throw Error('Exclusão não reduziu a duração da prévia');
  await page.getByTitle('Reproduzir prévia',{exact:true}).click();
  await page.waitForTimeout(400);
  if(await page.locator('.smooth-preview').getAttribute('data-playing')!=='true')throw Error('Ouvir deixou parada residual após exclusão');
  await page.getByTitle('Pausar prévia',{exact:true}).click();
  await page.getByRole('button',{name:'Desfazer',exact:true}).click();
  await waitReady();
  if(await page.locator('.cut-row').count())throw Error('Exclusão em lote não foi desfeita de uma vez');
  await page.getByRole('button',{name:'Refazer',exact:true}).click();
  await waitReady();
  if(await page.locator('.cut-row').count()!==total)throw Error('Refazer não recuperou o lote inteiro');
  await page.getByRole('button',{name:'Desfazer',exact:true}).click();
  await waitReady();
  const dryProject={version:1,videoPath:path.resolve('outputs/respiracoes-teste.mp4'),edit:{words:[{id:'fala-a',text:'Fala',start:0,end:1,paragraph:0},{id:'fala-b',text:'seguinte',start:2,end:6,paragraph:1}],cuts:[]}};
  fs.writeFileSync('outputs/projeto-corte-seco.json',JSON.stringify(dryProject));
  await page.locator('input[type=file]').nth(1).setInputFiles(path.resolve('outputs/projeto-corte-seco.json'));
  await page.locator('[data-word-id="fala-b"]').waitFor();await page.waitForFunction(()=>!document.querySelector('.job'));
  await page.getByRole('button',{name:'Excluir silêncios e respirações',exact:true}).click();
  await page.getByText(/cortes aplicados: silêncios e respirações/).waitFor({timeout:60000});
  await waitReady();
  if(await page.locator('.player-position').evaluate(e=>Number(e.max))>=6)throw Error('Limpeza unificada deixou video sem cortes');
  if(await page.locator('.cut-row').count()!==1)throw Error('Corte seco não aplicou o intervalo esperado');
  if(await page.getByLabel('Início',{exact:true}).inputValue()!=='1.00'||await page.getByLabel('Fim',{exact:true}).inputValue()!=='2.00')throw Error('Corte seco deixou margens');
  await page.getByRole('button',{name:'Desfazer',exact:true}).click();
  await waitReady();
  if(await page.locator('.cut-row').count())throw Error('Corte seco não é reversível');
  console.log('UI OK: importacao, miniaturas, selecao, exclusao, restauracao, desfazer/refazer, correcao, busca, Delete, ajustes de tempo, previa unica automatica, exportacao e layout.');
  await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
